//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentsViewAllData
    {
        public System.DateTime Date { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public string DoctorInfo { get; set; }
        public int CabinetNumber { get; set; }
        public string ClientInfo { get; set; }
    }
}
